### ISSUE TITLE
Reloads ship destroyed

### ISSUE THREAD

**Issue by SorenDiederik** [dolkensp/HoloXPLOR#12] opened 2016-02-28 04:05 UTC
After using your HoloXPLOR to fix my issue of my Turret not working every time I get blown up and head back to port, when I reload my ship it reappears post blown up. Picture shown in link below.

http://imgur.com/z4w5hvC
Using Google Chrome
file name db_SorenDiederik.xml

Submitted Report to CIG too

https://robertsspaceindustries.com/community/issue-council/star-citizen-alpha/SC-12113-F7C_re-spawns_a_heaping_slag_of_metal_I_previously_died_in_after_use_of_3rd_Party_Holo_Table_app_

**Comment by dolkensp** [comment] 2016-02-28 13:04
Glad you've reported it there too.

I've grabbed your file to take a look at, but this isn't really a state that HoloXPLOR can create (it only configures initial loadout. If this were HoloXPLOR, I'd expect it to manifest as a trashed ship the second it loads in your hangar, not only after a flight out)

Were you doing this in the PTU or Live?

Also, have you reproduced this across multiple restarts of the game? I've occasionally come across the Universe glitching the loadout of your ships, but re-requesting or restarting the game usually fixes it.

And final question - have you tried deleting your file, restarting your game (creates a fresh file), then using that with HoloXPLOR to make sure there was nothing funny with it before you started? The bug I normally see with this particular mount is that HoloXPLOR doesn't let you mount ANYTHING due to a bug with it when it's downloaded from Turbulent, but not yet used.

**Comment by SorenDiederik** [comment] 2016-02-28 23:22
Only in the Universe, not the newest PTU. And this has occurred on multiple
restarts of the game. I'm fixing to do a shadowplay capture of it all soon.
I've also opened a ticket with CIG. I just deleted the file and am fixing
to try again all over from scratch. I don't really know what is going on
but figured I'd let you guys know while I trouble shoot on my end.

https://robertsspaceindustries.com/community/issue-council/star-citizen-alpha/SC-12113-F7C_re-spawns_a_heaping_slag_of_metal_I_previously_died_in_after_use_of_3rd_Party_Holo_Table_app_

**Comment by stevencheatham** [comment] 2016-03-31 14:25
Its definitely not HoloXPLOR. Its a bug in the game client, I've seen stock load outs do that.

**Comment by SorenDiederik** [comment] 2016-03-31 15:05
Ok, thanks. I've managed to fix it now on my own and it was a few patches
ago. Thanks for looking into it anyways.

**Comment by dolkensp** [comment] 2016-03-31 15:32
Awesome, I'll close this then - I suspect next patch it will all be moot anyways :P

**Closed by dolkensp** 2016-03-31 15:32 UTC
Labels: bug
