### ISSUE TITLE
Equipping a S3 mount into Avenger does not enable an S2 weapon slot

### ISSUE THREAD

**Issue by dlikhten** [dolkensp/HoloXPLOR#14] opened 2016-03-04 02:29 UTC
I am able to equip the specialized Avenger nose cannon via the specialized s3 mount, but using a regular S3 gimbal mount doesn't give me an S2 slot.

**Comment by dolkensp** [comment] 2016-03-08 11:48
I recommend trying to refresh your XML file as follows:

1. Delete the XML file from the USER/database directory
2. Launch Star Citizen
3. Launch the Hangar
4. Exit Star Citizen
5. Re-upload your XML file

If the slot still isn't appearing, send me the link to the ship and I'll take a look. Some items come down corrupt from Turbulent unfortunately, I'm still working on a way to "patch" them automatically.

**Comment by dolkensp** [comment] 2016-03-29 01:58
@dlikhten did you have any luck with this?

**Comment by Reevor** [comment] 2016-03-30 12:17
I have a similar problem with a Sabre - it has worked in the past but over the last few days replacing the gimbal does not produce an extra S2 slot.

**Comment by dolkensp** [comment] 2016-03-30 13:24
Hi @Reevor 

I can confirm the XML you uploaded was missing ports on those gimbals.

Can you also try deleting and re-uploading your XML.

Sounds like there are more and more issues with empty guns and gimbals coming down from Turbulent - I may need to prioritize patching broken items tonight :\

**Comment by Reevor** [comment] 2016-03-30 17:57
Thanks for rapid feedback. Just tried again but no joy. Look forward to you fixing turbulents mess. 

Many thanks - your system so much better

Best wishes

Reevor/Iain

**Comment by dolkensp** [comment] 2016-04-12 01:01
This should be fixed - let me know if it's still an issue

**Closed by dolkensp** 2016-04-12 01:01 UTC
Labels: bug

**Comment by Reevor** [comment] 2016-04-19 18:06
Thanks. Seems to be working fine. 

Iain
